{% set name = "earth-osm" %}
{% set version = "2.3.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/earth_osm-{{ version }}.tar.gz
  sha256: 674187fcfbb99bab8a741a08e27e9444975f0f7ac81630789f43e0af48ba3ba4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - earth_osm = earth_osm.__main__:main
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - geopandas
    - pandas
    - tqdm
    - requests
    - protobuf >=4.21.1

test:
  imports:
    - earth_osm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypsa-meets-earth.github.io/
  dev_url: https://github.com/pypsa-meets-earth/earth-osm/
  summary: Python tool to extract large-amounts of OpenStreetMap data
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    earth-osm is a free software tool that can extract large-amounts
    of OpenStreetMap data. It implements filters and multi-processing
    for fast and memory-efficient computations. You can extract e.g.
    power lines for the whole Africa on your laptop. It builds on
    esy-osmfilter and improves its package design, usability and performance.

extra:
  recipe-maintainers:
    - pz-max
    - mnm-matin
    - davide-f
